-- AlterTable
ALTER TABLE "public"."food_entries" ADD COLUMN "portionSizeGrams" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "public"."food_entries" ADD COLUMN "caloriesPer100g" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "public"."food_entries" ADD COLUMN "proteinPer100g" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "public"."food_entries" ADD COLUMN "carbsPer100g" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "public"."food_entries" ADD COLUMN "fatPer100g" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "public"."food_entries" ADD COLUMN "fiberPer100g" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "public"."food_entries" ADD COLUMN "saltPer100g" DOUBLE PRECISION NOT NULL DEFAULT 0;